{
 "title": "Page Counter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"host.docker.internal:9091\"}"
    }
   ]
  },
  {
   "title": "Home Page",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{exported_job=\"FastAPI\", path=\"/\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{exported_job=\"FastAPI\", path=\"/error\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_bucket{exported_job=\"FastAPI\", path=\"/metrics\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}